#!/usr/bin/with-contenv bash

UMASK_SET=${UMASK_SET:-022}
WEBUI_PORT=${WEBUI_PORT:-8080}

umask "$UMASK_SET"

s6-svwait -u /var/run/s6/services/qbittorrent/

exec \
	s6-setuidgid abc /usr/bin/qbittorrent-nox --webui-port="${WEBUI_PORT}"

