#!/usr/bin/with-contenv bash

UMASK_SET=${UMASK_SET:-022}

umask "$UMASK_SET"

if [ -n "$NET_LOCAL" ]; then
  docker_network_gw="$(ip route | awk '/default/{print $3}')"
  ip route add $NET_LOCAL via $docker_network_gw dev eth0
else
  echo nameserver 8.8.8.8 > /etc/resolv.conf
fi

exec \
	/usr/sbin/openvpn --config /config/openvpn.conf

